-- MySQL Script generated by MySQL Workbench
-- Mon Dec 14 19:07:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autopozicovna
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autopozicovna
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autopozicovna` DEFAULT CHARACTER SET utf8 ;
USE `autopozicovna` ;

-- -----------------------------------------------------
-- Table `autopozicovna`.`auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autopozicovna`.`auto` ;

CREATE TABLE IF NOT EXISTS `autopozicovna`.`auto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meno` VARCHAR(50) NOT NULL,
  `cena` DOUBLE NOT NULL,
  `km` DOUBLE NOT NULL,
  `typ` VARCHAR(45) NOT NULL,
  `img_path` VARCHAR(80) NOT NULL,
  `rok` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autopozicovna`.`rezervacia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autopozicovna`.`rezervacia` ;

CREATE TABLE IF NOT EXISTS `autopozicovna`.`rezervacia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `od` DATE NULL,
  `do` DATE NULL,
  `auto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rezervacia_auto_idx` (`auto_id` ASC) VISIBLE,
  CONSTRAINT `fk_rezervacia_auto`
    FOREIGN KEY (`auto_id`)
    REFERENCES `autopozicovna`.`auto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autopozicovna`.`ziadost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autopozicovna`.`ziadost` ;

CREATE TABLE IF NOT EXISTS `autopozicovna`.`ziadost` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meno` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `priezvisko` VARCHAR(45) NOT NULL,
  `popis` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
